services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: always
    mem_limit: 128m
    mem_reservation: 64m
    ports:
      - "${TAILSCALE_IP}:3001:3001"
    volumes:
      - /home/smakosz/kuma/data:/app/data
