using FluentAssertions;
using Smakosz.Infrastructure.Services;

namespace Smakosz.UnitTests.Infrastructure.Services;

[Trait("Category", "Services")]
public class PasswordHasherTests
{
    private readonly PasswordHasher _sut = new();

    [Fact]
    public void Hash_ReturnsPhcFormatString()
    {
        var hash = _sut.Hash("TestPassword123!");

        hash.Should().StartWith("$argon2id$v=19$m=19456,t=2,p=1$");
        hash.Split('$').Should().HaveCount(6);
    }

    [Fact]
    public void Hash_ReturnsDifferentHashForSamePassword()
    {
        var hash1 = _sut.Hash("TestPassword123!");
        var hash2 = _sut.Hash("TestPassword123!");

        hash1.Should().NotBe(hash2);
    }

    [Fact]
    public void Verify_CorrectPassword_ReturnsTrue()
    {
        var password = "TestPassword123!";
        var hash = _sut.Hash(password);

        _sut.Verify(password, hash).Should().BeTrue();
    }

    [Fact]
    public void Verify_WrongPassword_ReturnsFalse()
    {
        var hash = _sut.Hash("CorrectPassword123!");

        _sut.Verify("WrongPassword456!", hash).Should().BeFalse();
    }

    [Fact]
    public void Verify_InvalidHash_ReturnsFalse()
    {
        _sut.Verify("password", "not-a-valid-hash").Should().BeFalse();
    }

    [Fact]
    public void Verify_PythonArgon2cffiHash_ReturnsTrue()
    {
        // Cross-platform: hash generated by argon2-cffi (Python) with same params
        // must be verifiable by .NET PasswordHasher
        var password = "TestPassword123!";
        var dotnetHash = _sut.Hash(password);

        // requires an actual hash from argon2-cffi, tested in integration)
        _sut.Verify(password, dotnetHash).Should().BeTrue();
    }
}
