<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Smakosz.Orchestrator</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ErrorOr" Version="2.*" />
    <PackageReference Include="Hangfire.Core" Version="1.8.*" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.*" />
    <PackageReference Include="Hangfire.PostgreSql" Version="1.20.*" />
    <PackageReference Include="MediatR" Version="12.*" />

  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Smakosz.Application\Smakosz.Application.csproj" />
    <ProjectReference Include="..\Smakosz.Infrastructure\Smakosz.Infrastructure.csproj" />
  </ItemGroup>
</Project>
